import random
from typing import List, Tuple
from core.optimization_problem import OptimizationProblem


class NQueensProblem(OptimizationProblem):
    """
    N-Queens optimization problem.
    State representation: A tuple of length N, where state[i] is the row index of the queen in column i.
    Objective: Maximize the number of NON-attacking pairs of queens.
               The maximum possible value is N * (N - 1) / 2.
    """

    def __init__(self, n: int, initial_state: Tuple[int, ...] = None):
        self.n = n
        if initial_state is None:
            initial_state = self.get_random_state()
        super().__init__(initial_state)
        self.max_fitness = (n * (n - 1)) // 2

    def value(self, state: Tuple[int, ...]) -> float:
        """
        Returns the number of non-attacking pairs of queens.
        Maximum is N * (N - 1) / 2.
        """
        attacking = 0
        for i in range(self.n):
            for j in range(i + 1, self.n):
                # Check same row
                if state[i] == state[j]:
                    attacking += 1
                # Check diagonals
                elif abs(state[i] - state[j]) == abs(i - j):
                    attacking += 1
        return self.max_fitness - attacking

    def get_random_neighbor(self, state: Tuple[int, ...]) -> Tuple[int, ...]:
        """
        Returns a random neighbor by moving one random queen to a different row in its column.
        """
        state_list = list(state)
        col = random.randint(0, self.n - 1)
        # Pick a random row different from the current one
        row = random.randint(0, self.n - 2)
        if row >= state_list[col]:
            row += 1
        state_list[col] = row
        return tuple(state_list)

    def get_all_neighbors(self, state: Tuple[int, ...]) -> List[Tuple[int, ...]]:
        """
        Returns all possible neighbors. A neighbor is generated by moving a single queen
        to a different row in its column. Total neighbors = N * (N - 1).
        """
        neighbors = []
        for col in range(self.n):
            for row in range(self.n):
                if state[col] != row:
                    new_state = list(state)
                    new_state[col] = row
                    neighbors.append(tuple(new_state))
        return neighbors

    def get_random_state(self) -> Tuple[int, ...]:
        """
        Generates a random state (one queen per column).
        """
        return tuple(random.randint(0, self.n - 1) for _ in range(self.n))

    def crossover(self, state1: Tuple[int, ...], state2: Tuple[int, ...]) -> Tuple[Tuple[int, ...], Tuple[int, ...]]:
        """
        Single-point crossover for Genetic Algorithm.
        """
        crossover_point = random.randint(1, self.n - 1)
        child1 = state1[:crossover_point] + state2[crossover_point:]
        child2 = state2[:crossover_point] + state1[crossover_point:]
        return child1, child2

    def mutate(self, state: Tuple[int, ...]) -> Tuple[int, ...]:
        """
        Mutates the state by moving one random queen to a random row.
        """
        return self.get_random_neighbor(state)
