import math
import random
from typing import List, Tuple
from core.optimization_problem import OptimizationProblem


class TSPProblem(OptimizationProblem):
    """
    Traveling Salesperson optimization problem.
    State representation: A tuple of city indices representing the tour.
    Objective: MINIMIZE the total distance of the tour.
               Since OptimizationProblem assumes maximization, we return negative distance.
    """

    def __init__(self, cities: List[Tuple[float, float]], initial_state: Tuple[int, ...] = None):
        """
        cities: List of (x, y) coordinates for each city.
        """
        self.cities = cities
        self.n = len(cities)
        
        # Precompute distances
        self.distances = [[0.0 for _ in range(self.n)] for _ in range(self.n)]
        for i in range(self.n):
            for j in range(self.n):
                if i != j:
                    dx = cities[i][0] - cities[j][0]
                    dy = cities[i][1] - cities[j][1]
                    self.distances[i][j] = math.sqrt(dx*dx + dy*dy)
                    
        if initial_state is None:
            initial_state = self.get_random_state()
            
        super().__init__(initial_state)

    def value(self, state: Tuple[int, ...]) -> float:
        """
        Returns negative distance of the tour (since we want to maximize value).
        The tour is a closed loop, so we include the distance from the last city back to the first.
        """
        dist = 0.0
        for i in range(self.n):
            dist += self.distances[state[i - 1]][state[i]]
        return -dist

    def get_random_neighbor(self, state: Tuple[int, ...]) -> Tuple[int, ...]:
        """
        Returns a random neighbor using a 2-opt swap.
        A 2-opt swap reverses the order of the cities between two random indices.
        """
        i, j = sorted(random.sample(range(self.n), 2))
        
        state_list = list(state)
        state_list[i:j+1] = reversed(state_list[i:j+1])
        return tuple(state_list)

    def get_all_neighbors(self, state: Tuple[int, ...]) -> List[Tuple[int, ...]]:
        """
        Returns all possible neighbors generated by a 2-opt swap.
        Total neighbors = N * (N - 1) / 2.
        """
        neighbors = []
        for i in range(self.n - 1):
            for j in range(i + 1, self.n):
                new_state = list(state)
                new_state[i:j+1] = reversed(new_state[i:j+1])
                neighbors.append(tuple(new_state))
        return neighbors

    def get_random_state(self) -> Tuple[int, ...]:
        """
        Returns a random permutation of cities.
        """
        state = list(range(self.n))
        random.shuffle(state)
        return tuple(state)

    def crossover(self, state1: Tuple[int, ...], state2: Tuple[int, ...]) -> Tuple[Tuple[int, ...], Tuple[int, ...]]:
        """
        Ordered Crossover (OX1) for TSP.
        Maintains valid permutations (no duplicate cities).
        """
        def ox1(p1, p2):
            start, end = sorted(random.sample(range(self.n), 2))
            child = [-1] * self.n
            # Copy segment from p1
            child[start:end+1] = p1[start:end+1]
            
            # Fill remaining from p2
            p2_filtered = [c for c in p2 if c not in child]
            
            idx = 0
            for i in range(self.n):
                if child[i] == -1:
                    child[i] = p2_filtered[idx]
                    idx += 1
            return tuple(child)

        child1 = ox1(state1, state2)
        child2 = ox1(state2, state1)
        return child1, child2

    def mutate(self, state: Tuple[int, ...]) -> Tuple[int, ...]:
        """
        Mutates the state using a 2-opt swap.
        """
        return self.get_random_neighbor(state)
